# Generated by Django 4.1 on 2023-01-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('categoy', models.CharField(choices=[('Musique', 'Musique'), ('Sport', 'Sport'), ('Cinema', 'Cinema')], max_length=10)),
                ('state', models.BooleanField(default=False)),
                ('nbr_participant', models.IntegerField(default=0)),
                ('evt_date', models.DateTimeField(null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
