# Generated by Django 4.1 on 2023-02-20 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_event_please check out the event date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='Please check out the event date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='categoy',
            new_name='category',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('evt_date__gte', datetime.datetime(2023, 2, 20, 9, 48, 57, 899516))), name='Please check out the event date'),
        ),
    ]
