# Generated by Django 4.1 on 2023-02-24 14:57

from django.db import migrations, models
import person.models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0002_alter_person_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="cin",
            field=models.CharField(
                max_length=8,
                primary_key=True,
                serialize=False,
                validators=[person.models.is_cin_length],
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[person.models.is_mail_esprit],
                verbose_name="Email",
            ),
        ),
    ]
